**import required libraries**

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Dataframe display
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_column',None)

# Customer Dataset Cleaning

**loading the data_sets**

In [3]:
customer_df =pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/customers.csv')

**Basic check pipeline**

In [4]:
def basic_check(df):
    print(50*'=','DataSet Shape',50*'=')
    print(df.shape)
    print(50*'=','Variables Dtypes',50*'=')
    print(df.info())
    print(50*'=','Checking for dataset duplication',50*'=')
    print(df.duplicated().sum())
    print(50*'=','checking for dataset missingness',50*'=')
    print(df.isna().sum())
    print(50*'=','checking for dataset percentage missingness',50*'=')
    print((df.isna().sum()/len(df))*100)
    print('=' * 50, 'Statistical Summary', '=' * 50)
    display(df.describe().T)
    print('=' * 50, 'Categorical Summary', '=' * 50)
    display(df.describe(include=['object', 'category']).T)

In [5]:
customer_df.head(5)

  customer_id registration_date customer_segment customer_status
0   CUST00001        2022-01-01         Frequent          Active
1   CUST00002        2022-01-01          Regular          Active
2   CUST00003        2022-01-01         Frequent          Active
3   CUST00004        2022-01-02       Occasional          Active
4   CUST00005        2022-01-02   Basket-builder          Active

In [6]:
basic_check(customer_df)

================================================== DataSet Shape ==================================================
(8000, 4)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        8000 non-null   str
 1   registration_date  8000 non-null   str
 2   customer_segment   8000 non-null   str
 3   customer_status    8000 non-null   str
dtypes: str(4)
memory usage: 250.1 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
customer_id          0
registration_date    0
customer_segment     0
customer_status      0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
customer_id          0.0
registration_date    0.0
customer_segment     0.0
customer_status      0.0
dtype: float64
================================================== Statistical Summary ==================================================

                  count unique         top  freq
customer_id        8000   8000   CUST00001     1
registration_date  8000   1453  2025-03-03    16
customer_segment   8000      5  Occasional  2779
customer_status    8000      2      Active  6694

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                  count unique         top  freq
customer_id        8000   8000   CUST00001     1
registration_date  8000   1453  2025-03-03    16
customer_segment   8000      5  Occasional  2779
customer_status    8000      2      Active  6694

**Converting date variable to correct date format**

In [7]:
customer_df['registration_date']=pd.to_datetime(customer_df['registration_date'],format='mixed',errors='coerce')

**Categorical columms entries standardization**

In [8]:
cust_cat_cols = customer_df.select_dtypes(include='object').columns.to_list()

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3802574139.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cust_cat_cols = customer_df.select_dtypes(include='object').columns.to_list()

In [9]:
cust_cat_cols

['customer_id', 'customer_segment', 'customer_status']

**checking unique entries**

In [10]:
for col in cust_cat_cols[1:]:
    display(customer_df[col].unique())

<StringArray>
['Frequent', 'Regular', 'Occasional', 'Basket-builder', 'Promo-driven']
Length: 5, dtype: str

<StringArray>
['Active', 'Inactive']
Length: 2, dtype: str

**saving the cleaned customer dataset**

In [11]:
customer_df.to_pickle('customer_clean.pkl')

# Inventory_movements Dataset Cleaning

**loading the dataset**

In [12]:
invent_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/inventory_movements.csv')

In [13]:
invent_df.head(10)

,movement_id,movement_datetime,store_id,product_id,movement_type,quantity_change,reference_type,reference_id,adjustment_reason
0,MOV0000001,2025-01-01 08:16:31,ST02,P122,Sale,-1,Sale,TXN0000001,NaN
1,MOV0000002,2025-01-01 08:28:56,ST12,P057,Sale,-1,Sale,TXN0000002,NaN
2,MOV0000003,2025-01-01 08:28:56,ST12,P079,Sale,-2,Sale,TXN0000002,NaN
3,MOV0000004,2025-01-01 08:59:06,ST06,P056,Sale,-1,Sale,TXN0000003,NaN
4,MOV0000005,2025-01-01 09:00:44,ST02,P044,Sale,-1,Sale,TXN0000004,NaN
5,MOV0000006,2025-01-01 09:00:44,ST02,P062,Sale,-2,Sale,TXN0000004,NaN
6,MOV0000007,2025-01-01 09:02:10,ST02,P022,Sale,-1,Sale,TXN0000005,NaN
7,MOV0000008,2025-01-01 09:08:13,ST01,P086,Sale,-1,Sale,TXN0000006,NaN
8,MOV0000009,2025-01-01 09:08:13,ST01,P072,Sale,-1,Sale,TXN0000006,NaN
9,MOV0000010,2025-01-01 09:08:13,ST01,P106,Sale,-1,Sale,TXN0000006,NaN

**Basic_check**

In [14]:
basic_check(invent_df)

================================================== DataSet Shape ==================================================
(270156, 9)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 270156 entries, 0 to 270155
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   movement_id        270156 non-null  str
 1   movement_datetime  270156 non-null  str
 2   store_id           270156 non-null  str
 3   product_id         270156 non-null  str
 4   movement_type      270156 non-null  str
 5   quantity_change    270156 non-null  int64
 6   reference_type     270156 non-null  str
 7   reference_id       265190 non-null  str
 8   adjustment_reason  4966 non-null    str
dtypes: int64(1), str(8)
memory usage: 18.6 MB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
movement_id               0
movement_datetime         0
store_id                  0
product_id                0
movement_type             0
quantity_change           0
reference_type            0
reference_id           4966
adjustment_reason    265190
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
movement_id           0.000000
movement_datetime     0.000000
store_id              0.000000
product_id            0.000000
movement_type         0.000000
quantity_change       0.000000
reference_type        0.000000
reference_id          1.838197
adjustment_reason    98.161803
dtype: float64
================================================== Statistical Summary ==================================================

                    count     mean       std   min  25%  50%  75%    max
quantity_change  270156.0  0.00885  5.539322 -18.0 -1.0 -1.0 -1.0  130.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                    count  unique                  top    freq
movement_id        270156  270156           MOV0000001       1
movement_datetime  270156  110325  2025-10-11 07:09:17      13
store_id           270156      12                 ST01   29891
product_id         270156     150                 P001    8168
movement_type      270156       5                 Sale  244272
reference_type     270156       4                 Sale  244272
reference_id       265190  105654             PO005108      13
adjustment_reason    4966       7              Expired    1242

**Converting_Date variable to correct date format**

In [15]:
invent_df['movement_datetime']=pd.to_datetime(invent_df['movement_datetime'],format='mixed',errors='coerce')

**Dealing with the missingness**

In [16]:
#droping the adjustment_reason column it has 98% missing entries
invent_df.drop(columns=['adjustment_reason'],inplace=True)

In [17]:
#inputing a placeholder in reference_id with about 1.8% missingness(place_holder = write_offs/adjustments)
invent_df['reference_id']=invent_df['reference_id'].fillna('write_offs/adjustments')

**Checking for unique values in categorical columns and standardizing the entries**

In [18]:
invent_cat_cols = invent_df.select_dtypes(include='str').columns.tolist()
invent_cat_cols

['movement_id',
 'store_id',
 'product_id',
 'movement_type',
 'reference_type',
 'reference_id']

In [19]:
for col in invent_cat_cols[3:5]:
    display(invent_df[col].unique())

<StringArray>
['Sale', 'Adjustment', 'Write-off', 'Receipt', 'Return']
Length: 5, dtype: str

<StringArray>
['Sale', 'Adjustment', 'Purchase order', 'Return']
Length: 4, dtype: str

**saving the clean inventory movement dataset**

In [20]:
invent_df.to_pickle("inventory_movement_clean.pkl")

# Lost_sales_log Dataset Cleaning

**loading the dataset**

In [21]:
lost_sales_log_df= pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/lost_sales_log.csv')

In [22]:
lost_sales_log_df.head(10)

,transaction_id,transaction_date,store_id,product_id,quantity_demanded,quantity_fulfilled,outcome
0,TXN0001330,2025-01-07,ST07,P107,1,0,Line dropped - no stock
1,TXN0002166,2025-01-10,ST07,P107,1,0,Line dropped - no stock
2,TXN0002263,2025-01-11,ST07,P107,1,0,Line dropped - no stock
3,TXN0002320,2025-01-11,ST07,P060,2,1,Partially filled
4,TXN0002911,2025-01-14,ST07,P107,1,0,Line dropped - no stock
5,TXN0002995,2025-01-14,ST07,P103,1,0,Line dropped - no stock
6,TXN0003547,2025-01-17,ST11,P008,1,0,Transaction voided - no stock
7,TXN0003708,2025-01-18,ST11,P083,2,0,Line dropped - no stock
8,TXN0003835,2025-01-18,ST11,P083,1,0,Line dropped - no stock
9,TXN0003858,2025-01-18,ST11,P008,2,0,Line dropped - no stock

**Basic Check**

In [23]:
basic_check(lost_sales_log_df)

================================================== DataSet Shape ==================================================
(2002, 7)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 2002 entries, 0 to 2001
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      2002 non-null   str
 1   transaction_date    2002 non-null   str
 2   store_id            2002 non-null   str
 3   product_id          2002 non-null   str
 4   quantity_demanded   2002 non-null   int64
 5   quantity_fulfilled  2002 non-null   int64
 6   outcome             2002 non-null   str
dtypes: int64(2), str(5)
memory usage: 109.6 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
transaction_id        0
transaction_date      0
store_id              0
product_id            0
quantity_demanded     0
quantity_fulfilled    0
outcome               0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
transaction_id        0.0
transaction_date      0.0
store_id              0.0
product_id            0.0
quantity_demanded     0.0
quantity_fulfilled    0.0
outcome               0.0
dtype: float64
================================================== Statistical Summary ==================================================

                     count      mean      std  min  25%  50%  75%  max
quantity_demanded   2002.0  1.427073  0.68534  1.0  1.0  1.0  2.0  5.0
quantity_fulfilled  2002.0  0.157842  0.46147  0.0  0.0  0.0  0.0  4.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                 count unique                      top  freq
transaction_id    2002   1976               TXN0015932     2
transaction_date  2002    329               2025-12-10    19
store_id          2002     12                     ST01   261
product_id        2002    144                     P062   104
outcome           2002      3  Line dropped - no stock  1587

**converting date column to correct Dtype**

In [24]:
lost_sales_log_df['transaction_date'] = pd.to_datetime(lost_sales_log_df['transaction_date'],format='mixed',errors='coerce')

**Checking categorical columns entries unique values and standardization**

In [25]:
lost_sl_cat_col =lost_sales_log_df.select_dtypes(include='str').columns.to_list()
lost_sl_cat_col

['transaction_id', 'store_id', 'product_id', 'outcome']

In [26]:
lost_sales_log_df['outcome'].unique()

<StringArray>
['Line dropped - no stock', 'Partially filled',
 'Transaction voided - no stock']
Length: 3, dtype: str

**saving the clean lost_sales log dataset**

In [27]:
lost_sales_log_df.to_pickle("lost_sales_log_clean.pkl")

# Opening Inventory Dataset Cleaning

**loading the dataset**

In [28]:
open_invent_df = pd.read_csv("/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/opening_inventory.csv")

In [29]:
open_invent_df.head(10)

  store_id product_id  opening_quantity  as_of_date
0     ST01       P001               120  2024-12-31
1     ST01       P002                20  2024-12-31
2     ST01       P003                61  2024-12-31
3     ST01       P004                22  2024-12-31
4     ST01       P005                20  2024-12-31
5     ST01       P006                49  2024-12-31
6     ST01       P007                40  2024-12-31
7     ST01       P008                15  2024-12-31
8     ST01       P009                37  2024-12-31
9     ST01       P010                16  2024-12-31

**Basic Checks**

In [30]:
basic_check(open_invent_df)

================================================== DataSet Shape ==================================================
(1800, 4)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   store_id          1800 non-null   str
 1   product_id        1800 non-null   str
 2   opening_quantity  1800 non-null   int64
 3   as_of_date        1800 non-null   str
dtypes: int64(1), str(3)
memory usage: 56.4 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
store_id            0
product_id          0
opening_quantity    0
as_of_date          0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
store_id            0.0
product_id          0.0
opening_quantity    0.0
as_of_date          0.0
dtype: float64
================================================== Statistical Summary ==================================================

                   count       mean        std  min  25%   50%   75%    max
opening_quantity  1800.0  17.378333  14.575852  2.0  8.0  13.0  21.0  147.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

           count unique         top  freq
store_id    1800     12        ST01   150
product_id  1800    150        P001    12
as_of_date  1800      1  2024-12-31  1800

**Converting the date_variable to correct Dtype**

In [31]:
open_invent_df['as_of_date']=pd.to_datetime(open_invent_df['as_of_date'],format='mixed',errors='coerce')

In [32]:
open_invent_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   store_id          1800 non-null   str
 1   product_id        1800 non-null   str
 2   opening_quantity  1800 non-null   int64
 3   as_of_date        1800 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 56.4 KB

**saving the clean opening inventory dataset**

In [33]:
open_invent_df.to_pickle("Open_inventory_clean.pkl")

# Prices Changes Dataset Cleaning

**Loading the dataset**

In [34]:
price_changes_df = pd.read_csv("/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/price_changes.csv")

**Basic Checks**

In [35]:
basic_check(price_changes_df)

================================================== DataSet Shape ==================================================
(30, 5)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         30 non-null     str
 1   effective_date     30 non-null     str
 2   new_unit_cost      30 non-null     float64
 3   new_selling_price  30 non-null     float64
 4   reason             30 non-null     str
dtypes: float64(2), str(3)
memory usage: 1.3 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
product_id           0
effective_date       0
new_unit_cost        0
new_selling_price    0
reason               0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
product_id           0.0
effective_date       0.0
new_unit_cost        0.0
new_selling_price    0.0
reason               0.0
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
new_unit_cost,30.0,152.396333,118.638582,23.6,58.725,121.3,214.1425,406.95
new_selling_price,30.0,210.666667,169.440730,31.0,78.500,162.5,292.5000,580.00

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

               count unique                               top freq
product_id        30     30                              P088    1
effective_date    30     28                        2025-04-13    2
reason            30      1  Simulated supplier cost increase   30

**converting date variable to corrrect Dtype**

In [36]:
price_changes_df['effective_date'] = pd.to_datetime(price_changes_df['effective_date'],format='mixed',errors='coerce')

**Saving the cleanded price_changes dataset**

In [37]:
price_changes_df.to_pickle('price_changes_cleaned.pkl')

# Products Dataset Cleaning

**Loading the dataset**

In [38]:
products_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/products.csv')

In [39]:
products_df.head(10)

,product_id,product_name,active_ingredient,strength,dosage_form,category,unit_of_measure,unit_cost,selling_price,product_status
0,P001,Paracetamol 500 mg Tablets,Paracetamol,500 mg,Tablets,Pain & Fever,pack of 20 tablets,28.86,44.0,Active
1,P002,Paracetamol 120 mg/5 mL Syrup,Paracetamol,120 mg/5 mL,Syrup,Pain & Fever,bottle of 60 mL,44.35,57.0,Active
2,P003,Ibuprofen 400 mg Tablets,Ibuprofen,400 mg,Tablets,Pain & Fever,strip of 10 tablets,33.78,45.0,Active
3,P004,Ibuprofen 200 mg Tablets,Ibuprofen,200 mg,Tablets,Pain & Fever,strip of 10 tablets,23.91,35.0,Active
4,P005,Ibuprofen 100 mg/5 mL Suspension,Ibuprofen,100 mg/5 mL,Suspension,Pain & Fever,bottle of 100 mL,88.14,110.0,Active
5,P006,Diclofenac 50 mg Tablets,Diclofenac,50 mg,Tablets,Pain & Fever,strip of 10 tablets,33.73,45.0,Active
6,P007,Diclofenac 1% Gel,Diclofenac,1%,Gel,Pain & Fever,tube of 30 g,121.18,160.0,Active
7,P008,Aspirin 75 mg Tablets,Aspirin,75 mg,Tablets,Pain & Fever,pack of 28 tablets,55.20,73.0,Discontinued
8,P009,Mefenamic acid 500 mg Capsules,Mefenamic acid,500 mg,Capsules,Pain & Fever,strip of 10 capsules,40.43,51.0,Active
9,P010,Naproxen 250 mg Tablets,Naproxen,250 mg,Tablets,Pain & Fever,strip of 10 tablets,46.98,69.0,Active

**Basic Check**

In [40]:
basic_check(products_df)

================================================== DataSet Shape ==================================================
(150, 10)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         150 non-null    str
 1   product_name       150 non-null    str
 2   active_ingredient  136 non-null    str
 3   strength           132 non-null    str
 4   dosage_form        150 non-null    str
 5   category           150 non-null    str
 6   unit_of_measure    150 non-null    str
 7   unit_cost          150 non-null    float64
 8   selling_price      150 non-null    float64
 9   product_status     150 non-null    str
dtypes: float64(2), str(8)
memory usage: 11.8 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
product_id            0
product_name          0
active_ingredient    14
strength             18
dosage_form           0
category              0
unit_of_measure       0
unit_cost             0
selling_price         0
product_status        0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
product_id            0.000000
product_name          0.000000
active_ingredient     9.333333
strength             12.000000
dosage_form           0.000000
category              0.000000
unit_of_measure       0.000000
unit_cost             0.000000
selling_price         0.000000
product_status        0.000000
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
unit_cost,150.0,155.935600,149.23495,22.3,61.15,108.785,200.73,913.17
selling_price,150.0,213.613333,207.13536,29.0,84.25,150.000,266.25,1360.00

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                  count unique                         top freq
product_id          150    150                        P001    1
product_name        150    150  Paracetamol 500 mg Tablets    1
active_ingredient   136    120                   Ibuprofen    3
strength            132     70                      500 mg   14
dosage_form         150     25                     Tablets   68
category            150     13                 Antibiotics   19
unit_of_measure     150     53         strip of 10 tablets   22
product_status      150      2                      Active  145

**Checking uniqueness and standardizing categorical variables**

In [41]:
product_cat_cols = products_df.select_dtypes(include='str').columns.to_list()
product_cat_cols

['product_id',
 'product_name',
 'active_ingredient',
 'strength',
 'dosage_form',
 'category',
 'unit_of_measure',
 'product_status']

In [42]:
for col in product_cat_cols[1:]:
    display(products_df[col].unique())

<StringArray>
[            'Paracetamol 500 mg Tablets',
          'Paracetamol 120 mg/5 mL Syrup',
               'Ibuprofen 400 mg Tablets',
               'Ibuprofen 200 mg Tablets',
       'Ibuprofen 100 mg/5 mL Suspension',
               'Diclofenac 50 mg Tablets',
                      'Diclofenac 1% Gel',
                  'Aspirin 75 mg Tablets',
         'Mefenamic acid 500 mg Capsules',
                'Naproxen 250 mg Tablets',
 ...
                      'Adhesive plasters',
                   'Crepe bandage 7.5 cm',
                      'Cotton wool 100 g',
                    'Sterile gauze swabs',
                    'Digital thermometer',
          'Disposable examination gloves',
         'Alcohol hand sanitiser 70% Gel',
                    'Surgical face masks',
              'Syringes with needle 5 mL',
 'Malaria rapid diagnostic test Test kit']
Length: 150, dtype: str

<StringArray>
[                    'Paracetamol',                       'Ibuprofen',
                      'Diclofenac',                         'Aspirin',
                  'Mefenamic acid',                        'Naproxen',
                      'Etoricoxib',               'Methyl salicylate',
                       'Piroxicam',                     'Amoxicillin',
 ...
                        'Nystatin',                      'Ivermectin',
                       'Aciclovir',                  'Levonorgestrel',
 'Levonorgestrel/Ethinylestradiol',             'Medroxyprogesterone',
                 'Povidone iodine',                 'Surgical spirit',
               'Hydrogen peroxide',          'Alcohol hand sanitiser']
Length: 121, dtype: str

<StringArray>
[               '500 mg',           '120 mg/5 mL',                '400 mg',
                '200 mg',           '100 mg/5 mL',                 '50 mg',
                    '1%',                 '75 mg',                '250 mg',
                 '90 mg',                   '25%',                 '20 mg',
           '250 mg/5 mL',                '625 mg',           '200 mg/5 mL',
                '100 mg',                '480 mg',           '240 mg/5 mL',
                   '1 g',             '20/120 mg', '20/120 mg dispersible',
             '40/320 mg',                 '60 mg',                '300 mg',
             '500/25 mg',                  '5 mg',                 '10 mg',
                 '25 mg',  '20 mg (slow release)',                 '40 mg',
                '850 mg',                 '80 mg',                  '2 mg',
             '100 IU/mL',             '50 strips',           '100 lancets',
                     nan,            '1 L sachet',     '20 mg dispersible',
           '3.35 g/5 mL',          '100 mcg/dose',             '2 mg/5 mL',
                  '4 mg',             '4 mg/5 mL',            '15 mg/5 mL',
                  '0.1%',         '600 mg/400 IU',               '1000 IU',
               '1000 mg',                '400 IU',              '1000 mcg',
                 '0.05%',                    '2%',                    '8%',
                    '5%',                   '15%',                  '0.5%',
                  '0.3%',                  '0.9%',                '150 mg',
         '100,000 IU/mL',                  '3 mg',                '1.5 mg',
            '150/30 mcg',             '150 mg/mL',                   '10%',
                    '6%',                '7.5 cm',                 '100 g',
                   '70%',                  '5 mL']
Length: 71, dtype: str

<StringArray>
[         'Tablets',            'Syrup',       'Suspension',
              'Gel',         'Capsules',         'Ointment',
        'Injection',      'Test strips',            'Other',
           'Powder', 'Chewable tablets',          'Inhaler',
      'Nasal drops', 'Softgel capsules',            'Cream',
           'Lotion',          'Shampoo',        'Eye drops',
     'Eye ointment',        'Ear drops',      'Nasal spray',
  'Oral suspension',          'Pessary',         'Test kit',
         'Solution']
Length: 25, dtype: str

<StringArray>
[                'Pain & Fever',                  'Antibiotics',
                'Antimalarials',               'Cardiovascular',
                     'Diabetes',             'Gastrointestinal',
        'Respiratory & Allergy',       'Vitamins & Supplements',
                  'Dermatology',              'Eye, Ear & Nose',
        'Other Anti-infectives',          'Reproductive Health',
 'First Aid & Medical Supplies']
Length: 13, dtype: str

<StringArray>
[  'pack of 20 tablets',      'bottle of 60 mL',  'strip of 10 tablets',
     'bottle of 100 mL',         'tube of 30 g',   'pack of 28 tablets',
 'strip of 10 capsules',   'pack of 10 tablets',    'pack of 3 tablets',
   'pack of 5 capsules',  'pack of 10 capsules',          'vial of 1 g',
   'pack of 14 tablets',    'pack of 4 tablets',   'pack of 24 tablets',
   'pack of 12 tablets',        'vial of 60 mg',   'pack of 30 tablets',
   'pack of 60 tablets',        'vial of 10 mL',     'box of 50 strips',
   'box of 100 lancets',  'pack of 14 capsules',     'bottle of 200 mL',
  'strip of 6 capsules',               'sachet', 'inhaler of 200 doses',
      'bottle of 10 mL',  'pack of 30 capsules',         'tube of 20 g',
         'tube of 15 g',         'tube of 50 g',         'jar of 100 g',
         'tub of 500 g',       'bottle of 5 mL',          'tube of 5 g',
      'bottle of 15 mL',     'pack of 1 tablet',    'pack of 6 tablets',
    'pack of 1 capsule',      'bottle of 30 mL',   'pack of 25 tablets',
         'vial of 1 mL',    'pack of 1 pessary',            'pack of 3',
          'single test',           'pack of 10',           'pack of 20',
                 'roll',        'pack of 100 g',                 'each',
           'box of 100',            'box of 50']
Length: 53, dtype: str

<StringArray>
['Active', 'Discontinued']
Length: 2, dtype: str

**Dealing with missing values**

In [43]:
products_df=products_df.fillna({
    'active_ingredient':'Not Provided',
    'strength':'Not Provided'
})

**Saving Cleaned prodducts dataset**

In [44]:
products_df.to_pickle ("Products_clean.pkl")

# Cleaning Promotion dataset

**Loading the dataset**

In [45]:
promotion_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/promotions.csv')
promotion_df.head(10)

,promotion_id,promotion_name,promotion_type,product_id,category,start_date,end_date,discount_type,discount_value
0,PROMO001,Hydrochlorothiazide 25 mg Tablets - 5% off,Product-level,P045,NaN,2025-01-07,2025-01-20,Percentage,5.0
1,PROMO002,Dermatology promotion - 10% off,Category-level,NaN,Dermatology,2025-01-10,2025-01-16,Percentage,10.0
2,PROMO003,Surgical spirit Solution - 20% off,Product-level,P139,NaN,2025-01-11,2025-01-24,Percentage,20.0
3,PROMO004,Omega-3 fish oil 1000 mg Softgel capsules - 20% off,Product-level,P099,NaN,2025-01-18,2025-01-27,Percentage,20.0
4,PROMO005,Other Anti-infectives promotion - 5% off,Category-level,NaN,Other Anti-infectives,2025-01-23,2025-02-05,Percentage,5.0
5,PROMO006,Other Anti-infectives promotion - 10% off,Category-level,NaN,Other Anti-infectives,2025-01-31,2025-02-20,Percentage,10.0
6,PROMO007,Dihydroartemisinin/Piperaquine 40/320 mg Tablets - 5% off,Product-level,P035,NaN,2025-02-08,2025-02-21,Percentage,5.0
7,PROMO008,Alcohol hand sanitiser 70% Gel - 20% off,Product-level,P147,NaN,2025-02-09,2025-03-01,Percentage,20.0
8,PROMO009,Mefenamic acid 500 mg Capsules - 20% off,Product-level,P009,NaN,2025-02-11,2025-02-17,Percentage,20.0
9,PROMO010,Azithromycin 500 mg Tablets - 20% off,Product-level,P017,NaN,2025-03-06,2025-03-15,Percentage,20.0

**Basics Check**

In [46]:
basic_check(promotion_df)

================================================== DataSet Shape ==================================================
(60, 9)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   promotion_id    60 non-null     str
 1   promotion_name  60 non-null     str
 2   promotion_type  60 non-null     str
 3   product_id      40 non-null     str
 4   category        20 non-null     str
 5   start_date      60 non-null     str
 6   end_date        60 non-null     str
 7   discount_type   60 non-null     str
 8   discount_value  60 non-null     float64
dtypes: float64(1), str(8)
memory usage: 4.3 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
promotion_id       0
promotion_name     0
promotion_type     0
product_id        20
category          40
start_date         0
end_date           0
discount_type      0
discount_value     0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
promotion_id       0.000000
promotion_name     0.000000
promotion_type     0.000000
product_id        33.333333
category          66.666667
start_date         0.000000
end_date           0.000000
discount_type      0.000000
discount_value     0.000000
dtype: float64
================================================== Statistical Summary ==================================================

                count       mean       std  min   25%   50%   75%   max
discount_value   60.0  12.416667  5.711397  5.0  8.75  10.0  20.0  20.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

               count unique                                        top freq
promotion_id      60     60                                   PROMO001    1
promotion_name    60     56  Other Anti-infectives promotion - 10% off    2
promotion_type    60      2                              Product-level   40
product_id        40     40                                       P045    1
category          20     11                                Dermatology    3
start_date        60     56                                 2025-04-21    3
end_date          60     56                                 2025-05-01    2
discount_type     60      2                                 Percentage   49

**Converting date variables to correct date format**

In [47]:
date_col = ['start_date','end_date']
for col in date_col:
    promotion_df[col]=pd.to_datetime(promotion_df[col],format='mixed',errors='coerce')

**Dealing with missingness**

In [48]:
promotion_df=promotion_df.fillna({
    'product_id':'No Promotion',
    'category':'Not Provided'})

**Checking for categorical columns unique entries and standardizing**

In [49]:
promotion_cat_cols = promotion_df.select_dtypes(include='str').columns.to_list()
promotion_cat_cols

['promotion_id',
 'promotion_name',
 'promotion_type',
 'product_id',
 'category',
 'discount_type']

In [50]:
for col in promotion_cat_cols[1:]:
    print(promotion_df[col].unique())

<StringArray>
[               'Hydrochlorothiazide 25 mg Tablets - 5% off',
                           'Dermatology promotion - 10% off',
                        'Surgical spirit Solution - 20% off',
       'Omega-3 fish oil 1000 mg Softgel capsules - 20% off',
                  'Other Anti-infectives promotion - 5% off',
                 'Other Anti-infectives promotion - 10% off',
 'Dihydroartemisinin/Piperaquine 40/320 mg Tablets - 5% off',
                  'Alcohol hand sanitiser 70% Gel - 20% off',
                  'Mefenamic acid 500 mg Capsules - 20% off',
                     'Azithromycin 500 mg Tablets - 20% off',
                           'Lancets 100 lancets - KES 5 off',
              'Beclometasone 100 mcg/dose Inhaler - 15% off',
                 'Respiratory & Allergy promotion - 10% off',
                        'Famotidine 20 mg Tablets - 20% off',
                          'Antimalarials promotion - 5% off',
                     'Domperidone 10 mg Tablets - KES 5 off',
                    'Vitamin B complex Tablets - KES 20 off',
                   'Ferrous sulfate 200 mg Tablets - 5% off',
                       'Clotrimazole 1% Ear drops - 15% off',
                 'Respiratory & Allergy promotion - 15% off',
                   'Reproductive Health promotion - 10% off',
                'Vitamins & Supplements promotion - 10% off',
                 'Ciprofloxacin 500 mg Tablets - KES 20 off',
                    'Montelukast 10 mg Tablets - KES 20 off',
                       'Eye, Ear & Nose promotion - 15% off',
                            'Adhesive plasters - KES 10 off',
                           'Pain & Fever promotion - 5% off',
                 'Xylometazoline 0.1% Nasal drops - 15% off',
                         'Antimalarials promotion - 10% off',
                         'Benzoyl peroxide 5% Gel - 10% off',
             'Albendazole 400 mg Chewable tablets - 20% off',
                            'Dermatology promotion - 5% off',
                      'Amlodipine 5 mg Tablets - KES 20 off',
                       'Prednisolone 5 mg Tablets - 15% off',
                         'Naproxen 250 mg Tablets - 10% off',
                     'Fluconazole 150 mg Capsules - 15% off',
                           'Antibiotics promotion - 10% off',
                         'Ketoconazole 2% Shampoo - 20% off',
                              'Diabetes promotion - 15% off',
                          'Quinine 300 mg Tablets - 10% off',
             'Hyoscine butylbromide 10 mg Tablets - 15% off',
                             'Sterile gauze swabs - 10% off',
                         'Gliclazide 80 mg Tablets - 5% off',
           'First Aid & Medical Supplies promotion - 5% off',
           'Nystatin 100,000 IU/mL Oral suspension - 5% off',
                          'Permethrin 5% Cream - KES 20 off',
                     'Magnesium 250 mg Tablets - KES 10 off',
                          'Surgical face masks - KES 10 off',
                'Ferrous sulfate/Folic acid Syrup - 15% off',
    'Human insulin (isophane) 100 IU/mL Injection - 15% off',
          'First Aid & Medical Supplies promotion - 10% off',
                         'Ivermectin 3 mg Tablets - 20% off',
                            'Terbinafine 1% Cream - 20% off',
                  'Flucloxacillin 500 mg Capsules - 20% off',
                     'Petroleum jelly Ointment - KES 15 off',
      'Sulfadoxine/Pyrimethamine 500/25 mg Tablets - 5% off']
Length: 56, dtype: str
<StringArray>
['Product-level', 'Category-level']
Length: 2, dtype: str
<StringArray>
[        'P045', 'No Promotion',         'P139',         'P099',
         'P035',         'P147',         'P009',         'P017',
         'P061',         'P084',         'P075',         'P072',
         'P091',         'P095',         'P123',         'P018',
         'P083',         'P141',         'P088',         'P112',
         'P125',         'P039',         'P089',         'P010',
         'P127',         'P114',         'P037',         'P071',
         'P144',         'P056',         'P128',         'P115',
         'P102',         'P148',         'P096',         'P059',
         'P129',         'P108',         'P027',         'P113',
         'P038']
Length: 41, dtype: str
<StringArray>
[                'Not Provided',                  'Dermatology',
        'Other Anti-infectives',        'Respiratory & Allergy',
                'Antimalarials',          'Reproductive Health',
       'Vitamins & Supplements',              'Eye, Ear & Nose',
                 'Pain & Fever',                  'Antibiotics',
                     'Diabetes', 'First Aid & Medical Supplies']
Length: 12, dtype: str
<StringArray>
['Percentage', 'Fixed amount']
Length: 2, dtype: str

**Saving clean promotion dataset**

In [51]:
promotion_df.to_pickle('promotion_clean.pkl')

# Purchase order items Cleaning

**Loading the dataset**

In [52]:
purchase_oi_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/purchase_order_items.csv')
purchase_oi_df.head(10)

,purchase_order_id,line_id,product_id,quantity_ordered,quantity_received,unit_purchase_cost
0,PO000001,1,P010,10,10,47.86
1,PO000001,2,P028,6,6,105.28
2,PO000001,3,P066,10,10,42.03
3,PO000001,4,P069,10,10,33.03
4,PO000002,1,P020,12,12,85.66
5,PO000002,2,P030,3,3,305.23
6,PO000002,3,P120,6,6,124.85
7,PO000003,1,P032,6,6,61.41
8,PO000003,2,P064,6,6,122.31
9,PO000003,3,P071,12,12,84.52

**Basic Checks**

In [53]:
basic_check(purchase_oi_df)

================================================== DataSet Shape ==================================================
(20584, 6)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 20584 entries, 0 to 20583
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   purchase_order_id   20584 non-null  str
 1   line_id             20584 non-null  int64
 2   product_id          20584 non-null  str
 3   quantity_ordered    20584 non-null  int64
 4   quantity_received   20584 non-null  int64
 5   unit_purchase_cost  20584 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 965.0 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
purchase_order_id     0
line_id               0
product_id            0
quantity_ordered      0
quantity_received     0
unit_purchase_cost    0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
purchase_order_id     0.0
line_id               0.0
product_id            0.0
quantity_ordered      0.0
quantity_received     0.0
unit_purchase_cost    0.0
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
line_id,20584.0,2.677274,1.773957,1.00,1.00,2.000,4.0000,13.00
quantity_ordered,20584.0,16.396862,11.528800,2.00,9.00,12.000,20.0000,150.00
quantity_received,20584.0,15.647445,11.538344,0.00,9.00,12.000,20.0000,130.00
unit_purchase_cost,20584.0,155.735247,149.457175,21.63,61.75,109.195,196.3825,940.32

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                   count unique       top freq
purchase_order_id  20584   6593  PO005108   13
product_id         20584    150      P062  195

**casting line_id to str dtype**

In [54]:
purchase_oi_df['line_id']=purchase_oi_df['line_id'].astype('str')

**Saving the clean purchase order item**

In [55]:
purchase_oi_df.to_pickle('purchase_order_item_clean.pkl')

# Purchase order Dataset Cleaning

**Loading the dataset**

In [56]:
purchase_order_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/purchase_orders.csv')
purchase_order_df

,purchase_order_id,supplier_id,store_id,order_date,expected_delivery_date,order_status
0,PO000001,SUP01,ST11,2025-01-01,2025-01-06,Completed
1,PO000002,SUP02,ST11,2025-01-01,2025-01-07,Completed
2,PO000003,SUP03,ST11,2025-01-01,2025-01-06,Completed
3,PO000004,SUP04,ST11,2025-01-01,2025-01-06,Completed
4,PO000005,SUP05,ST11,2025-01-01,2025-01-06,Cancelled
...,...,...,...,...,...,...
6588,PO006589,SUP17,ST12,2025-12-31,2026-01-04,Open
6589,PO006590,SUP19,ST12,2025-12-31,2026-01-04,Open
6590,PO006591,SUP20,ST12,2025-12-31,2026-01-05,Open
6591,PO006592,SUP21,ST12,2025-12-31,2026-01-02,Open
6592,PO006593,SUP24,ST12,2025-12-31,2026-01-03,Open

**Basic Checks**

In [57]:
basic_check(purchase_order_df)

================================================== DataSet Shape ==================================================
(6593, 6)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 6593 entries, 0 to 6592
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   purchase_order_id       6593 non-null   str
 1   supplier_id             6593 non-null   str
 2   store_id                6593 non-null   str
 3   order_date              6593 non-null   str
 4   expected_delivery_date  6593 non-null   str
 5   order_status            6593 non-null   str
dtypes: str(6)
memory usage: 309.2 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
purchase_order_id         0
supplier_id               0
store_id                  0
order_date                0
expected_delivery_date    0
order_status              0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
purchase_order_id         0.0
supplier_id               0.0
store_id                  0.0
order_date                0.0
expected_delivery_date    0.0
order_status              0.0
dtype: float64
================================================== Statistical Summary ==================================================

                       count unique         top  freq
purchase_order_id       6593   6593    PO000001     1
supplier_id             6593     24       SUP03   314
store_id                6593     12        ST11   560
order_date              6593    183  2025-01-19    69
expected_delivery_date  6593    370  2025-05-27    34
order_status            6593      4   Completed  5227

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                       count unique         top  freq
purchase_order_id       6593   6593    PO000001     1
supplier_id             6593     24       SUP03   314
store_id                6593     12        ST11   560
order_date              6593    183  2025-01-19    69
expected_delivery_date  6593    370  2025-05-27    34
order_status            6593      4   Completed  5227

**converting date column to correct date format**

In [58]:
purchase_order_df['order_date']=pd.to_datetime(purchase_order_df['order_date'],format='mixed',errors='coerce')

**Checking categorical columns uniqueness and standardizing**

In [59]:
purchase_order_df['order_status'].unique()

<StringArray>
['Completed', 'Cancelled', 'Partially received', 'Open']
Length: 4, dtype: str

**Saving Clean purchase_order dataset**

In [60]:
purchase_order_df.to_pickle('purchase_order_clean.pkl')

# Sales Return items Dataset cleaning

**Loading the dataset**

In [61]:
sales_return_items_df=pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/sales_return_items.csv')
sales_return_items_df.head(10)

,return_id,line_id,product_id,quantity_returned,unit_refund_amount,restockable
0,RET000001,1,P142,1,150.0,False
1,RET000002,1,P138,1,185.0,True
2,RET000003,1,P081,1,34.0,True
3,RET000004,1,P085,1,150.0,True
4,RET000005,1,P127,1,175.0,False
5,RET000006,1,P071,1,125.0,True
6,RET000007,1,P063,1,225.0,True
7,RET000008,1,P085,1,150.0,True
8,RET000008,2,P097,1,395.0,True
9,RET000009,1,P105,1,99.0,True

**Basic Checks**

In [62]:
basic_check(sales_return_items_df)

================================================== DataSet Shape ==================================================
(1271, 6)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 1271 entries, 0 to 1270
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   return_id           1271 non-null   str
 1   line_id             1271 non-null   int64
 2   product_id          1271 non-null   str
 3   quantity_returned   1271 non-null   int64
 4   unit_refund_amount  1271 non-null   float64
 5   restockable         1271 non-null   bool
dtypes: bool(1), float64(1), int64(2), str(2)
memory usage: 51.0 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
return_id             0
line_id               0
product_id            0
quantity_returned     0
unit_refund_amount    0
restockable           0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
return_id             0.0
line_id               0.0
product_id            0.0
quantity_returned     0.0
unit_refund_amount    0.0
restockable           0.0
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
line_id,1271.0,1.189614,0.392150,1.0,1.0,1.0,1.0,2.0
quantity_returned,1271.0,1.057435,0.236122,1.0,1.0,1.0,1.0,3.0
unit_refund_amount,1271.0,162.133989,158.003318,28.9,61.0,110.0,180.0,1360.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

           count unique        top freq
return_id   1271   1030  RET000008    2
product_id  1271    148       P001   57

**line_id casting:str**

In [63]:
sales_return_items_df['line_id']=sales_return_items_df['line_id'].astype('str')

**Saving sales_return_items dataset cleaned**

In [64]:
sales_return_items_df.to_pickle('sales_return_items_clean.pkl')

# Sales Return Dataset Cleaning

**loading the dataset**

In [65]:
sales_return_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/sales_returns.csv')
sales_return_df.head(10)

,return_id,original_transaction_id,return_datetime,store_id,return_reason,refund_amount
0,RET000001,TXN0000029,2025-01-03 18:12:09,ST11,Product near expiry,150.0
1,RET000002,TXN0000802,2025-01-04 19:36:28,ST02,Wrong product dispensed,185.0
2,RET000003,TXN0000823,2025-01-05 01:52:24,ST02,Duplicate purchase,34.0
3,RET000004,TXN0001228,2025-01-06 22:55:17,ST01,Wrong product dispensed,150.0
4,RET000005,TXN0000152,2025-01-09 18:30:37,ST02,Damaged packaging,175.0
5,RET000006,TXN0000580,2025-01-09 23:41:17,ST03,Duplicate purchase,125.0
6,RET000007,TXN0001420,2025-01-10 15:00:36,ST06,Duplicate purchase,225.0
7,RET000008,TXN0001919,2025-01-11 04:26:23,ST03,Duplicate purchase,545.0
8,RET000009,TXN0002013,2025-01-11 14:09:31,ST11,Prescription changed,99.0
9,RET000010,TXN0000005,2025-01-12 09:19:10,ST02,Duplicate purchase,485.0

**Basic Checks**

In [66]:
basic_check(sales_return_df)

================================================== DataSet Shape ==================================================
(1030, 6)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   return_id                1030 non-null   str
 1   original_transaction_id  1030 non-null   str
 2   return_datetime          1030 non-null   str
 3   store_id                 1030 non-null   str
 4   return_reason            1030 non-null   str
 5   refund_amount            1030 non-null   float64
dtypes: float64(1), str(5)
memory usage: 48.4 KB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
return_id                  0
original_transaction_id    0
return_datetime            0
store_id                   0
return_reason              0
refund_amount              0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
return_id                  0.0
original_transaction_id    0.0
return_datetime            0.0
store_id                   0.0
return_reason              0.0
refund_amount              0.0
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
refund_amount,1030.0,210.403883,199.99419,29.0,83.0,150.0,262.25,1460.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                        count unique                    top freq
return_id                1030   1030              RET000001    1
original_transaction_id  1030   1030             TXN0000029    1
return_datetime          1030   1030    2025-01-03 18:12:09    1
store_id                 1030     12                   ST01  118
return_reason            1030      6  Customer changed mind  258

**converting date column to correct date format**

In [67]:
sales_return_df['return_datetime']=pd.to_datetime(sales_return_df['return_datetime'],format='mixed',errors='coerce')

**Checking categorical entries uniqueness and standardizing**

In [68]:
sales_return_df['return_reason'].unique()

<StringArray>
[    'Product near expiry', 'Wrong product dispensed',
      'Duplicate purchase',       'Damaged packaging',
    'Prescription changed',   'Customer changed mind']
Length: 6, dtype: str

**saving cleaned sales return dataset**

In [69]:
sales_return_df.to_pickle('sales_return_cleaned.pkl')

# Stores Dataset Cleaning

**Loading the dataset**

In [70]:
stores_df =pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/stores.csv')
stores_df.head(10)

,store_id,store_name,county,town,opening_date,store_status
0,ST01,SimPharm Westlands,Nairobi,Westlands,2016-03-14,Active
1,ST02,SimPharm Embakasi,Nairobi,Embakasi,2018-07-02,Active
2,ST03,SimPharm Nyali,Mombasa,Nyali,2017-02-20,Active
3,ST04,SimPharm Mombasa Island,Mombasa,Mombasa Island,2015-09-01,Active
4,ST05,SimPharm Milimani,Kisumu,Milimani,2019-05-13,Active
5,ST06,SimPharm Kisumu Central,Kisumu,Kisumu Central,2016-11-07,Active
6,ST07,SimPharm Nakuru Town,Nakuru,Nakuru Town,2017-06-19,Active
7,ST08,SimPharm Naivasha,Nakuru,Naivasha,2020-01-27,Active
8,ST09,SimPharm Thika,Kiambu,Thika,2018-03-12,Active
9,ST10,SimPharm Ruaka,Kiambu,Ruaka,2021-08-16,Active

**Basic Check**

In [71]:
basic_check(stores_df)

================================================== DataSet Shape ==================================================
(12, 6)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      12 non-null     str
 1   store_name    12 non-null     str
 2   county        12 non-null     str
 3   town          12 non-null     str
 4   opening_date  12 non-null     str
 5   store_status  12 non-null     str
dtypes: str(6)
memory usage: 708.0 bytes
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
store_id        0
store_name      0
county          0
town            0
opening_date    0
store_status    0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
store_id        0.0
store_name      0.0
county          0.0
town            0.0
opening_date    0.0
store_status    0.0
dtype: float64
================================================== Statistical Summary ==================================================

             count unique                 top freq
store_id        12     12                ST01    1
store_name      12     12  SimPharm Westlands    1
county          12      6             Nairobi    2
town            12     12           Westlands    1
opening_date    12     12          2016-03-14    1
store_status    12      1              Active   12

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

             count unique                 top freq
store_id        12     12                ST01    1
store_name      12     12  SimPharm Westlands    1
county          12      6             Nairobi    2
town            12     12           Westlands    1
opening_date    12     12          2016-03-14    1
store_status    12      1              Active   12

**converting date column to correct date format**

In [72]:
stores_df['opening_date']=pd.to_datetime(stores_df['opening_date'],format='mixed',errors='coerce')

**Checking categorical columns unique entries and standardizing**

In [73]:
stores_cat_cols = stores_df.select_dtypes(include='str').columns.tolist()
stores_cat_cols

['store_id', 'store_name', 'county', 'town', 'store_status']

In [74]:
for col in stores_cat_cols[1:]:
    print(stores_df[col].unique())

<StringArray>
[     'SimPharm Westlands',       'SimPharm Embakasi',
          'SimPharm Nyali', 'SimPharm Mombasa Island',
       'SimPharm Milimani', 'SimPharm Kisumu Central',
    'SimPharm Nakuru Town',       'SimPharm Naivasha',
          'SimPharm Thika',          'SimPharm Ruaka',
   'SimPharm Eldoret Town',         'SimPharm Langas']
Length: 12, dtype: str
<StringArray>
['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Kiambu', 'Uasin Gishu']
Length: 6, dtype: str
<StringArray>
[     'Westlands',       'Embakasi',          'Nyali', 'Mombasa Island',
       'Milimani', 'Kisumu Central',    'Nakuru Town',       'Naivasha',
          'Thika',          'Ruaka',   'Eldoret Town',         'Langas']
Length: 12, dtype: str
<StringArray>
['Active']
Length: 1, dtype: str

**Saving the clean store dataset**

In [75]:
stores_df.to_pickle('stores_clean.pkl')

# Suppliers Dataset Clean

**Loading the datset**

In [76]:
suppliers_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/suppliers.csv')
suppliers_df.head(10)

,supplier_id,supplier_name,supplier_type,supplier_status
0,SUP01,SIM Supplier 01 (Pharmaceutical),Pharmaceutical wholesaler,Active
1,SUP02,SIM Supplier 02 (Pharmaceutical),Pharmaceutical wholesaler,Inactive
2,SUP03,SIM Supplier 03 (Pharmaceutical),Pharmaceutical wholesaler,Active
3,SUP04,SIM Supplier 04 (Pharmaceutical),Pharmaceutical wholesaler,Active
4,SUP05,SIM Supplier 05 (Pharmaceutical),Pharmaceutical wholesaler,Active
5,SUP06,SIM Supplier 06 (Pharmaceutical),Pharmaceutical wholesaler,Active
6,SUP07,SIM Supplier 07 (Pharmaceutical),Pharmaceutical wholesaler,Active
7,SUP08,SIM Supplier 08 (Pharmaceutical),Pharmaceutical wholesaler,Active
8,SUP09,SIM Supplier 09 (Generic),Generic manufacturer distributor,Active
9,SUP10,SIM Supplier 10 (Generic),Generic manufacturer distributor,Active

**Basic Checks**

In [77]:
basic_check(suppliers_df)

================================================== DataSet Shape ==================================================
(24, 4)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   supplier_id      24 non-null     str
 1   supplier_name    24 non-null     str
 2   supplier_type    24 non-null     str
 3   supplier_status  24 non-null     str
dtypes: str(4)
memory usage: 900.0 bytes
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
supplier_id        0
supplier_name      0
supplier_type      0
supplier_status    0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
supplier_id        0.0
supplier_name      0.0
supplier_type      0.0
supplier_status    0.0
dtype: float64
================================================== Statistical Summary ==================================================

                count unique                               top freq
supplier_id        24     24                             SUP01    1
supplier_name      24     24  SIM Supplier 01 (Pharmaceutical)    1
supplier_type      24      5         Pharmaceutical wholesaler    8
supplier_status    24      2                            Active   22

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                count unique                               top freq
supplier_id        24     24                             SUP01    1
supplier_name      24     24  SIM Supplier 01 (Pharmaceutical)    1
supplier_type      24      5         Pharmaceutical wholesaler    8
supplier_status    24      2                            Active   22

**checking categorical column unique entries and standardizing**

In [78]:
suppliers_cat_cols = suppliers_df.select_dtypes(include='str').columns.tolist()
suppliers_cat_cols

['supplier_id', 'supplier_name', 'supplier_type', 'supplier_status']

In [79]:
for col in suppliers_cat_cols[1:]:
    print(suppliers_df[col].unique())

<StringArray>
['SIM Supplier 01 (Pharmaceutical)', 'SIM Supplier 02 (Pharmaceutical)',
 'SIM Supplier 03 (Pharmaceutical)', 'SIM Supplier 04 (Pharmaceutical)',
 'SIM Supplier 05 (Pharmaceutical)', 'SIM Supplier 06 (Pharmaceutical)',
 'SIM Supplier 07 (Pharmaceutical)', 'SIM Supplier 08 (Pharmaceutical)',
        'SIM Supplier 09 (Generic)',        'SIM Supplier 10 (Generic)',
        'SIM Supplier 11 (Generic)',        'SIM Supplier 12 (Generic)',
        'SIM Supplier 13 (Generic)',    'SIM Supplier 14 (Supplements)',
    'SIM Supplier 15 (Supplements)',    'SIM Supplier 16 (Supplements)',
            'SIM Supplier 17 (OTC)',            'SIM Supplier 18 (OTC)',
            'SIM Supplier 19 (OTC)',            'SIM Supplier 20 (OTC)',
        'SIM Supplier 21 (Medical)',        'SIM Supplier 22 (Medical)',
        'SIM Supplier 23 (Medical)',        'SIM Supplier 24 (Medical)']
Length: 24, dtype: str
<StringArray>
[          'Pharmaceutical wholesaler',    'Generic manufacturer distributor',
             'Supplements distributor', 'OTC and consumer health distributor',
        'Medical supplies distributor']
Length: 5, dtype: str
<StringArray>
['Active', 'Inactive']
Length: 2, dtype: str

**saving the clean supplier dataset**

In [80]:
suppliers_df.to_pickle('suppliers_clean.pkl')

# Transaction_items Dataset Cleaning

**Loading the dataset**

In [81]:
transaction_items_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/transaction_items.csv')
transaction_items_df.head(10)

,transaction_id,line_id,product_id,quantity,unit_price,discount_amount,unit_cost_at_sale,line_gross_amount,line_net_amount,promotion_id
0,TXN0000001,1,P122,1,120.0,0.0,87.71,120.0,120.0,NaN
1,TXN0000002,1,P057,1,200.0,0.0,137.06,200.0,200.0,NaN
2,TXN0000002,2,P079,2,48.0,0.0,36.69,96.0,96.0,NaN
3,TXN0000003,1,P056,1,160.0,0.0,125.81,160.0,160.0,NaN
4,TXN0000004,1,P044,1,145.0,0.0,111.82,145.0,145.0,NaN
5,TXN0000004,2,P062,2,80.0,0.0,60.07,160.0,160.0,NaN
6,TXN0000005,1,P022,1,485.0,0.0,369.67,485.0,485.0,NaN
7,TXN0000006,1,P086,1,150.0,0.0,103.20,150.0,150.0,NaN
8,TXN0000006,2,P072,1,81.0,0.0,54.63,81.0,81.0,NaN
9,TXN0000006,3,P106,1,175.0,0.0,134.48,175.0,175.0,NaN

**Basic Check**

In [82]:
basic_check(transaction_items_df)

================================================== DataSet Shape ==================================================
(247794, 10)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 247794 entries, 0 to 247793
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   transaction_id     247794 non-null  str
 1   line_id            247794 non-null  int64
 2   product_id         247794 non-null  str
 3   quantity           247794 non-null  int64
 4   unit_price         247794 non-null  float64
 5   discount_amount    247794 non-null  float64
 6   unit_cost_at_sale  247794 non-null  float64
 7   line_gross_amount  247794 non-null  float64
 8   line_net_amount    247794 non-null  float64
 9   promotion_id       16931 non-null   str
dtypes: float64(5), int64(2), str(3)
memory usage: 18.9 MB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
transaction_id            0
line_id                   0
product_id                0
quantity                  0
unit_price                0
discount_amount           0
unit_cost_at_sale         0
line_gross_amount         0
line_net_amount           0
promotion_id         230863
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
transaction_id        0.000000
line_id               0.000000
product_id            0.000000
quantity              0.000000
unit_price            0.000000
discount_amount       0.000000
unit_cost_at_sale     0.000000
line_gross_amount     0.000000
line_net_amount       0.000000
promotion_id         93.167308
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
line_id,247794.0,2.046910,1.147876,1.0,1.00,2.00,3.00,9.00
quantity,247794.0,1.278619,0.555435,1.0,1.00,1.00,1.00,8.00
unit_price,247794.0,164.366147,165.301689,29.0,65.00,110.00,175.00,1360.00
discount_amount,247794.0,1.502560,10.084893,0.0,0.00,0.00,0.00,816.00
unit_cost_at_sale,247794.0,120.697510,120.090213,22.3,46.55,85.69,130.75,913.17
line_gross_amount,247794.0,210.588198,258.602872,29.0,81.00,145.00,230.00,5440.00
line_net_amount,247794.0,209.085639,256.891558,28.9,81.00,145.00,230.00,5440.00

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                 count  unique         top  freq
transaction_id  247794  100000  TXN0001866     9
product_id      247794     150        P001  7928
promotion_id     16931      60    PROMO029  1464

**line_id casting:str**

In [83]:
transaction_items_df['line_id']=transaction_items_df['line_id'].astype('str')

**dealing with the missingness**

In [84]:
transaction_items_df['promotion_id'] = transaction_items_df['promotion_id'].fillna('NA')

**Saving Cleaned transaction_items dataset**

In [85]:
transaction_items_df.to_pickle('transaction_items_clean.pkl')

# transactions Dataset Cleaning

**Loading the dataset**

In [86]:
transaction_df = pd.read_csv('/Users/mac/DEV/Capstone_Project/pharmacy-customer-sales-intelligence/data/raw/Raw_data/transactions.csv')
transaction_df.head(10)

,transaction_id,transaction_datetime,store_id,customer_id,payment_method,transaction_status,currency_code,gross_amount,discount_amount,net_amount
0,TXN0000001,01/01/2025 08:16,ST02,CUST02120,Cash,Completed,KES,120,0.0,120.0
1,TXN0000002,01/01/2025 08:28,ST12,CUST04689,M-Pesa,Completed,KES,296,0.0,296.0
2,TXN0000003,01/01/2025 08:59,ST06,CUST03048,Insurance,Completed,KES,160,0.0,160.0
3,TXN0000004,01/01/2025 09:00,ST02,CUST00340,M-Pesa,Completed,KES,305,0.0,305.0
4,TXN0000005,01/01/2025 09:02,ST02,CUST00690,Cash,Completed,KES,485,0.0,485.0
5,TXN0000006,01/01/2025 09:08,ST01,NaN,Cash,Completed,KES,406,0.0,406.0
6,TXN0000007,01/01/2025 09:12,ST09,CUST01138,M-Pesa,Completed,KES,300,0.0,300.0
7,TXN0000008,01/01/2025 09:13,ST12,CUST03820,M-Pesa,Completed,KES,170,0.0,170.0
8,TXN0000009,01/01/2025 09:17,ST05,NaN,M-Pesa,Completed,KES,435,0.0,435.0
9,TXN0000010,01/01/2025 09:18,ST06,NaN,Cash,Completed,KES,165,0.0,165.0

**Basic Check**

In [87]:
basic_check(transaction_df)

================================================== DataSet Shape ==================================================
(100000, 10)
================================================== Variables Dtypes ==================================================
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  str
 1   transaction_datetime  100000 non-null  str
 2   store_id              100000 non-null  str
 3   customer_id           80000 non-null   str
 4   payment_method        100000 non-null  str
 5   transaction_status    100000 non-null  str
 6   currency_code         100000 non-null  str
 7   gross_amount          100000 non-null  int64
 8   discount_amount       100000 non-null  float64
 9   net_amount            100000 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 7.6 MB
None
================================================== Checking for dataset duplication ==================================================
0
================================================== checking for dataset missingness ==================================================
transaction_id              0
transaction_datetime        0
store_id                    0
customer_id             20000
payment_method              0
transaction_status          0
currency_code               0
gross_amount                0
discount_amount             0
net_amount                  0
dtype: int64
================================================== checking for dataset percentage missingness ==================================================
transaction_id           0.0
transaction_datetime     0.0
store_id                 0.0
customer_id             20.0
payment_method           0.0
transaction_status       0.0
currency_code            0.0
gross_amount             0.0
discount_amount          0.0
net_amount               0.0
dtype: float64
================================================== Statistical Summary ==================================================

,count,mean,std,min,25%,50%,75%,max
gross_amount,100000.0,521.824920,484.736571,29.0,200.0,391.0,681.0,7355.0
discount_amount,100000.0,3.723253,16.495340,0.0,0.0,0.0,0.0,816.0
net_amount,100000.0,518.101667,481.522265,28.9,200.0,390.0,676.0,7355.0

================================================== Categorical Summary ==================================================

/var/folders/qd/pr9pp5cj4q92_tmd1ms843f40000gn/T/ipykernel_18289/3289861715.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object', 'category']).T)

                       count  unique               top    freq
transaction_id        100000  100000        TXN0000001       1
transaction_datetime  100000   82905  18/10/2025 10:08       7
store_id              100000      12              ST01   11255
customer_id            80000    8000         CUST04965     158
payment_method        100000       4            M-Pesa   60115
transaction_status    100000       2         Completed   98504
currency_code         100000       1               KES  100000

**converting date column to correct date format**

In [88]:
transaction_df['transaction_datetime']=pd.to_datetime(transaction_df['transaction_datetime'],format='mixed',errors='coerce')

**checking the categorical columns entries uniqueness and standardization**

In [89]:
transaction_cat_col = transaction_df.select_dtypes(include='str').columns.tolist()
transaction_cat_col

['transaction_id',
 'store_id',
 'customer_id',
 'payment_method',
 'transaction_status',
 'currency_code']

In [90]:
for col in transaction_cat_col[3:]:
    print(transaction_df[col].unique())

<StringArray>
['Cash', 'M-Pesa', 'Insurance', 'Card']
Length: 4, dtype: str
<StringArray>
['Completed', 'Voided']
Length: 2, dtype: str
<StringArray>
['KES']
Length: 1, dtype: str

**saving cleaned transaction_dataset**

In [91]:
transaction_df.to_pickle('transactions_clean.pkl')